### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by G1R-Productions** [WoolScarf/Runelite-ReVerb#1]
What is an example configuration to change a verb option?

**Comment by WoolScarf** [comment]
You can see it by hovering over the text above the input box,

It's "MenuOption:Replacement", leading and trailing whitespace is trimmed, letting the list be made more readable. Hyphens and numbers are accepted, despite the instructions (I forgot to update the text!). Pairs are separated by semicolons.

Such that:
*  "Eat:Consume" is the same as "        Eat   :  Consume     ;"
*  "Walk here:Move" isn't the same as "Walk___here:Move" (replace underscores with spaces. Dunno why formatting won't let me put them here)
*  "Talk-To : Pester ; Drop : Yeet" is valid input.


I'll also add this to the Readme.
